var welcome_text = "<p>Welcome to the experiment. This experiment should take no longer than 20 minutes.</p> <p>Press any key to begin.</p>";

var instruction_text = "<p>Please read these instructions carefully.</p>"+"<p>This study is being conducted by Jackie Spear in the Department of Psychology. You will be asked to study a list of words, and then tested on your memory performance on these same words. At test, some of the words will be previously studied words, and some will be new. Your job will be to indicate that either yes, you did previously study a word, or no, you did not. The study is computer mediated and it takes approximately 20 minutes to complete. Also, when prompted to provide a word, respond by typing in the word 'puppy'. You will receive one credit in exchange for your participation. The researcher may be contacted by email at umspear@myumanitoba.ca.</p>"+"<p>Press any key to begin.</p>";

var instruction_text = "<p>Please read these instructions carefully.</p>"+"<p>This study is being conducted by Jackie Spear in the Department of Psychology. You will be asked to study a list of 40 word pairs, after which you will be given a memory test for the second word in each pair. When each word pair is presented, the second word will appear in either <span style=color:green>green</span> or <span style=color:red>red</span>. When the second word appears in <span style=color:green>green</span> font, your job will be to <b>type that second word</b>. Other times, you will see the second word appear in <span style=color:red>RED</span> font, where your job will be to do nothing, and <b>simply read that word silently.</b> Note that the words that you type will not show up on the screen, but will be recorded.</p><p>At test, some of the words will be previously studied words, and some will be new. Your job will be to indicate that either yes, you did previously study a word, or no, you did not. The study is computer mediated and takes approximately 20 minutes to complete. Also, when prompted to provide the answer, respond by typing in the answer to 2+2 = __. You will receive one credit in exchange for your participation. The researcher may be contacted by email at umspear@myumanitoba.ca.</p><p>Press any key to begin.</p>";

var post_practice_text = "<p>Remember! When you see the second word appear in <span style=color:green;font-weight:bold>GREEN FONT</span> you must <b>TYPE that second word.</b> When you see the second word appear in <span style=color:red;font-weight:bold>RED FONT</span>, your job will be to do nothing, and <b>simply READ that word silently.</b> Please only type or read the second word in each pair.</p>"+"<p>Typing is being recorded. Press 'w' to continue.</p>";


var attention_check_text = "Provide the answer:";

var fullscreen_prompt = "<p><b>Please turn off all background audio for the experiment</b>. Do not continue until you have turned off all other audio.</p>"+"<p>Also, remain in fullscreen mode for the entire experiment. The experiment will switch to full screen mode when you press the button below. It will also record if you exit fullscreen mode.</p>";

var debrief_text = "<p>In an elaborative processing experiment, participants are asked to study words that include some sort of elaborative processing, and some that do not. This form of elaborative processing can take on many forms, which include, but are not limited to, speaking words aloud, typing words, or trying to generate part of a word from an incomplete fragment or associated cue. When tested on recognition for these words, participants discriminate words that were studied in a training list from words that were not presented in the training list. Further, participants routinely have higher rates of recognition for words that were subjected to the elaborative processing manipulation than the words that were not (e.g. people remember words that they typed better than words that they just read). In conjunction with this, we are going to use a computational model of memory, called MINERVA 2, to derive predictions that are consistent with human performance. The ultimate goal of this research is to be able to derive predictions about elaborative processing that account for a number of related effects. You can learn more about this line of work from our laboratory webpage located at home.cc.umanitoba.ca/~jamiesor.</p><p>Press any key to finish the experiment.</p><br><p>Thank you for your help,<br>Jackie Spear<br>Ph.D. Student<br>Department of Psychology<br>University of Manitoba</p>";


var test_instruction_text = "<p>Take a rest if you need.</p>"+"<p>Next, your job will be to indicate whether you previously studied a word by pressing 'y', otherwise press 'n'. Keep your index fingers on these keys.</p>"+"<p>When you are ready press 'i' to continue.</p>";
